/* MEMORY ALLOCATION */
BUFF	EQU	0f000h		; START OF RAM, INPUT BUFFER
IOCON	EQU	BUFF+0FFh	; INPUT/OUTPUT CONFIGURATION
USROUT	EQU	IOCON+2		; USER SUPPLIED OUTPUT DEVICE VECTOR
CURSOR	EQU	USROUT+2	; CURSOR POSITION
LSTCHR	EQU	CURSOR+2	; CHARACTER UNDER CURSOR
STACK	EQU	0ffffh		; MACHINE STACK
TB	EQU	BUFF+50		; TEMPORARY TEXT BUFFER
XBF	EQU	TB+50		; EXTRA TEXT BUFFER
EDBUF	EQU	BUFF+256	; EDIT BUFFER
CS	EQU	EDBUF+0FAh	; CONTROL STACK SPACE
CSP	EQU	CS+1		; CONTROL STACK POINTER
ARYLOC	EQU	CSP+2		; LOCATION OF ARRAYS
SEED	EQU	ARYLOC+1	; RANDOM NUMBER SEED
VARS	EQU	SEED+2		; VARIABLE SPACE
VARTOP	EQU	0f6h		; VARS + 0400h, upper 8 bits only
RFLAG	EQU	VARS+52		; PROGRAM RUNNING FLAG
IFLAG	EQU	RFLAG+1		; INPUTTING FLAG
Pend	EQU	IFLAG+1		; POINTER TO END OF EXPRESSION
EFLAG	EQU	Pend+1		; ASSIGNMENT FLAG
DATA	EQU	EFLAG+1		; READ/DATA POINTER
LAST	EQU	DATA+2		; LAST FREE ARRAY SPACE
TEMP	EQU	LAST+2		; TEMPORARY STORAGE
cp1	equ	TEMP+10		; 4 vars for the compares
cp2	equ	cp1+1		;
cp3	equ	cp2+1		;
cp4	equ	cp3+1		;
rest7	equ	cp4+1		; restart7 vector
nmi	equ	rest7+2		; NMI vector
basic	equ	nmi+2		; basic start vector
rentry	equ	basic+2		; basic soft start
sleep	equ	rentry+2	; basic sleep counter value
kbd_reg	equ	sleep+2		; keyboard interupt counter
kbd_dat	equ	kbd_reg+1	; keyboard interupt counter
rtc_int	equ	kbd_dat+1	; stop RTC ints, 
TXT	EQU	08000h		; PROGRAM AND ARRAY STORAGE
DELETE	EQU	07Fh		; DELETE CHARACTER
